site_name: Zibersegurtasuna Web Garapenean
site_url: https://zibersegurtasun-fptxurdinaga.eus
site_author: FP Txurdinaga
site_description: Zibersegurtasunari buruzko ikasgaiak eta baliabideak

# Configuración del tema
theme:
  name: material
  palette:
    primary: '#0056b3'  # Azul corporativo
    accent: '#ff6b00'   # Naranja corporativo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.highlight
    - content.code.copy
    - navigation.top
  logo: assets/images/Logo_Home3.png
  favicon: assets/images/favicon-96x96-1.png
  icon:
    logo: material/library

# CSS personalizado
extra_css:
  - css/custom.css

nav:
  - Hasiera: index.md
  - '1. Oinarriak eta mehatxu arruntak':
    - '1.1. Web Garapenean Zibersegurtasunaren Sarrera': oinarriak_mehatxuak/sarrera.md
    - '1.2. Webaren funtzionamenduaren oinarriak': oinarriak_mehatxuak/web_oinarriak.md
    - '1.3. Web ahultasun arrunten ikuspegi orokorra': oinarriak_mehatxuak/owasp_top10.md
  - '2. Eraso eta defentsa oinarrizkoak':
    - '2.1. Injekzioen aurkako defentsak': eraso_defentsak/injekzioak.md
    - '2.2. Autentifikazio eta saioen segurtasuna': eraso_defentsak/autentifikazioa.md
    - '2.3. Sarbide-kontrola eta konfigurazio segurua': eraso_defentsak/sarbide_kontrola.md
  - '3. Datuen babesa eta tresna praktikoak':
    - '3.1. Datu sentikorren babesa': datu_babesa/datu_sentikorrak.md
    - '3.2. APIen eta dependentzien segurtasuna': datu_babesa/api_segurtasuna.md
    - '3.3. Tresna praktikoen sarrera': datu_babesa/tresnak.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
